<?php

namespace ConnexionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ETimeSheetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ETimeSheetRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function getEtsDuJour($promo = null){
        $date = new \DateTime();
        $date = $date->format("Y-m-d");
        $query = $this->createQueryBuilder('e')
            ->where('e.date LIKE :date')
            ->setParameter('date', '%'.$date.'%');
        if(!is_null($promo)){
            $query->andWhere('e.promotion = :promo')
               ->setParameter('promo', $promo);
        }
        return $query->getQuery()->getResult();
    }
}
