<?php

namespace ConnexionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MatiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatiereRepository extends EntityRepository
{
    public function getNbHeures($mois,$promotion,$matiere){
        return $this->createQueryBuilder('m')
            ->select('m','c')
            ->join('c.matiere', 'm')
            ->join('c.ets', 'e')
            ->where('e.date LIKE :date')
            ->andWhere('m.libelle ='. $matiere->libelle)
            ->andWhere('m.promotion ='.$promotion->id)
            ->setParameter('date', '%'.$mois.'%')
            ->groupBy('c.type')
            ->getQuery()
            ->getResult();
    }
}
