<?php

namespace ConnexionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * promotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class promotionRepository extends EntityRepository
{
}
