<?php

namespace ConnexionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * User_coursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User_coursRepository extends EntityRepository
{
}
