<?php

namespace ConnexionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends EntityRepository
{
    public function findByRole($roles) {
        $query = $this->_em->createQueryBuilder();
        $query->select('u')
            ->from($this->_entityName, 'u');
        foreach ($roles as $index => $role) {
            if($index == 0){
                $query->where('u.roles LIKE :role_'.$index)
                    ->setParameter('role_'.$index, '%'.$role.'%');
            }
            else{
                $query->orWhere('u.roles LIKE :role_'.$index)
                    ->setParameter('role_'.$index, '%'.$role.'%');
            }
        }

        return $query->getQuery()->getResult();
    }
}