<?php

namespace ConnexionBundle\Repository\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ETimeSheetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ETimeSheetRepository extends EntityRepository
{
}
